version: "3"
services:
  admin-db:
    image: mongo:5.0
    restart: ${RESTART_POLICY}
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$ADMIN_DB_ROOT"
      MONGO_INITDB_ROOT_PASSWORD: "$ADMIN_DB_ROOT_PASSWORD"
      MONGO_INITDB_DATABASE: "$MONGO_INITDB_DATABASE"
    volumes:
      - ./data:/data/db
      - ./containers/mongo:/docker-entrypoint-initdb.d:ro

  admin_php:
    build: ./containers/php
    restart: ${RESTART_POLICY}
    environment:
      ADMIN_API_TOKEN : "$ADMIN_API_TOKEN"
      ADMIN_API_SALT : "$ADMIN_API_SALT"
      DB_USER: "$ADMIN_DB_USER"
      DB_PASSWORD: "$ADMIN_DB_PASSWORD"
      DB_NAME: "$DB_NAME"
      DOMAIN: "$DOMAIN"
      START_ROOM_URL: "$START_ROOM_URL"
      SIDECAR_URL: "$SIDECAR_URL"
      ENABLE_SUAS_EXTENSIONS: "$ENABLE_SUAS_EXTENSIONS"
    volumes:
      - ./src:/var/www/html:ro
      - ./vendor:/var/www/vendor:ro

  composer:
    image: composer/composer
    command: ["composer", "install", "--ignore-platform-req=ext-mongodb"]
    volumes:
      - ./:/app

  admin:
    build: configuration/nginx
    restart: ${RESTART_POLICY}
    environment:
      DOMAIN: "$DOMAIN"
    depends_on:
      - admin_php
    volumes:
      - ./src:/var/www/html:ro
      - ./vendor:/var/www/vendor:ro
      - ./containers/nginx:/etc/nginx/templates
    labels:
      - "traefik.http.middlewares.strip-admin-prefix.stripprefix.prefixes=/admin"
      - "traefik.http.routers.admin.rule=(Host(`${DOMAIN}`) && PathPrefix(`/admin`))"
      - "traefik.http.routers.admin.middlewares=strip-admin-prefix@docker"
      - "traefik.http.routers.admin.entryPoints=web"
      - "traefik.http.services.admin.loadbalancer.server.port=80"
      - "traefik.http.routers.admin-ssl.rule=(Host(`${DOMAIN}`) && PathPrefix(`/admin`))"
      - "traefik.http.routers.admin-ssl.middlewares=strip-admin-prefix@docker"
      - "traefik.http.routers.admin-ssl.entryPoints=websecure"
      - "traefik.http.routers.admin-ssl.tls=true"
      - "traefik.http.routers.admin-ssl.service=admin"
      - "traefik.enable=true"
