  admin-db:
    image: mongo:8
    restart: ${RESTART_POLICY}
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$ADMIN_DB_ROOT"
      MONGO_INITDB_ROOT_PASSWORD: "$ADMIN_DB_ROOT_PASSWORD"
      MONGO_INITDB_DATABASE: "workadventure"
    volumes:
      - ./data:/data/db
      - ./database:/docker-entrypoint-initdb.d:ro
 
  admin_php:
    build: ../php
    restart: ${RESTART_POLICY}
    environment:
      ADMIN_API_TOKEN : "$ADMIN_API_TOKEN"
      ADMIN_API_SALT : "$ADMIN_API_SALT"
      DB_USER: "$ADMIN_DB_USER"
      DB_PASSWORD: "$ADMIN_DB_PASSWORD"
      DB_NAME: "workadventure"
      DOMAIN: "$DOMAIN"
      START_ROOM_URL: "$START_ROOM_URL"
    volumes:
      - ./src:/var/www/html:ro
      - ./vendor:/var/www/vendor:ro
    depends_on:
      - admin-db
      - sidecar

  composer:
    image: composer/composer
    command: ["composer", "install", "--ignore-platform-req=ext-mongodb"]
    volumes:
      - ./:/app

  admin:
    image: nginx:mainline
    restart: ${RESTART_POLICY}
    environment:
      DOMAIN: "$DOMAIN"
    depends_on:
      - admin_php
    volumes:
      - ./src:/var/www/html:ro
      - ./vendor:/var/www/vendor:ro
      - ./containers/nginx:/etc/nginx/templates
    labels:
      traefik.http.middlewares.strip-admin-prefix.stripprefix.prefixes: "/admin"
      traefik.http.routers.admin.rule: "(Host(`${DOMAIN}`) && PathPrefix(`/admin`))"
      traefik.http.routers.admin.middlewares: "strip-admin-prefix@docker"
      traefik.http.routers.admin.entryPoints: "web"
      traefik.http.services.admin.loadbalancer.server.port: "80"
      traefik.http.routers.admin-ssl.rule: "(Host(`${DOMAIN}`) && PathPrefix(`/admin`))"
      traefik.http.routers.admin-ssl.middlewares: "strip-admin-prefix@docker"
      traefik.http.routers.admin-ssl.entryPoints: "websecure"
      traefik.http.routers.admin-ssl.tls: "true"
      traefik.http.routers.admin-ssl.service: "admin"
      traefik.enable: "true"
